### ISSUE TITLE
It could work with nodejs v0.10

### ISSUE THREAD

**Issue by bad5anta** [stfsy/broccoli-image-min#1]
In nodejs v0.12 `toLowerCase()` became `toLower()`. So if replace method _matchingFileExtension with:

```
// index.js : 169
function _matchingFileExtension(relativePath) {
    // check if file has an aceptable extension to process
    // toLower() so it's not case sensitive
    var ext = path.extname(relativePath);
    if(typeof toLower == 'undefined')
        ext = ext.toLowerCase();
    else
        ext = ext.toLower();
    return acceptableExtensions.indexOf(ext) > -1;
}
```

it gonna work with nodejs v0.10 too.

P.S.: Please, add contibution information, so ppl could make pull requests.

**Comment by stfsy** [comment]
Guess i can close this one? @bad5anta still using broccoli and broccoli-image-min? Plugin should work on Broccoli >= 1 and Node >= 4.
